spring:
  application:
    name: campus-match
  profiles:
    active: local # 기본 프로필: local (로컬 개발 환경)
    # 프로필 우선순위: local > dev > prod > test
    # IntelliJ Run Configuration에서 -Dspring.profiles.active=local 또는 dev 설정 필요

  datasource:
    url: jdbc:mysql://localhost:3306/campus?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: campus
    password: campuspw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

# Swagger 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: Campus Match API
    description: 숙명여자대학교 캠퍼스 매치 플랫폼 API
    version: 1.0.0
    contact:
      name: Campus Match Team
      email: support@campus-match.com
  servers:
    - url: http://localhost:8080
      description: Local Development Server

jwt:
  secret: your-secret-key-here-make-it-long-and-secure-for-production-use-a-very-long-secret-key-at-least-256-bits
  access-token-expiration: 3600 # 1 hour in seconds
  refresh-token-expiration: 86400 # 24 hours in seconds
