# 개발 환경 설정
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

# 서버 포트 설정
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  # WHY: dev 환경에서 한글 URL 인코딩 문제 해결
  tomcat:
    uri-encoding: UTF-8
    relaxed-query-chars: "|,{,},[,],\\"
    relaxed-path-chars: "|,{,},[,],\\"
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: campus
    password: campuspw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: Asia/Seoul
  flyway:
    enabled: true
    clean-disabled: true
    clean-on-validation-error: false
    baseline-on-migrate: true

# 보안 로그 활성화
logging:
  level:
    org.springframework.security: DEBUG
    com.sookmyung.campus_match.config.security: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
