server:
  port: 8081

spring:
  datasource:
    # 127.0.0.1 사용 이유: localhost는 IPv6 우선순위로 인한 연결 문제 방지
    # allowPublicKeyRetrieval=true: MySQL 8.0+ 보안 정책으로 인한 연결 오류 해결
    # useSSL=false: 로컬 개발 환경에서 SSL 인증서 문제 방지
    url: jdbc:mysql://127.0.0.1:3306/campus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: campus
    password: campuspw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 커넥션 풀 설정으로 연결 안정성 향상
      maximum-pool-size: 10          # 최대 커넥션 수
      minimum-idle: 2                # 최소 유휴 커넥션 수
      connection-timeout: 30000      # 커넥션 타임아웃 (30초)
      validation-timeout: 5000       # 검증 타임아웃 (5초)
      idle-timeout: 600000           # 유휴 커넥션 타임아웃 (10분)
      max-lifetime: 1800000          # 커넥션 최대 수명 (30분)
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc.time_zone: Asia/Seoul
        default_batch_fetch_size: 100
        jdbc.batch_size: 50
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web: debug
    org.springframework.security: debug
    com.sookmyung.campus_match: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
