spring:
  application:
    name: campus-match
  profiles:
    active: local # 기본 프로필: local (로컬 개발 환경)
    # 프로필 우선순위: local > dev > prod > test
    # IntelliJ Run Configuration에서 -Dspring.profiles.active=local 또는 dev 설정 필요

  flyway:
    enabled: false # Flyway 사용 안 할 경우 비활성화

jwt:
  secret: your-secret-key-here-make-it-long-and-secure-for-production-use-a-very-long-secret-key-at-least-256-bits
  access-token-expiration: 3600 # 1 hour in seconds
  refresh-token-expiration: 86400 # 24 hours in seconds
